import java.awt.Container;

import javax.swing.*;

/**
 *
 * @author js595
 */
public class AccountView3 extends  JFrame {

    /**
     * Creates new form AccountView3
     */
    public AccountView3(Container rootPane) {
    	
    	this.rootPane =  rootPane;
        initComponents();    	
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new  JPanel();
        jLabel1 = new  JLabel();
        jLabel2 = new  JLabel();
        jLabel3 = new  JLabel();
        jScrollPane1 = new  JScrollPane();
        jPanel2 = new  JPanel();
        jLabel4 = new  JLabel();
        jLabel5 = new  JLabel();
        jTextField11 = new  JTextField();
        jLabel6 = new  JLabel();
        jTextField13 = new  JTextField();
        jLabel7 = new  JLabel();
        jTextField15 = new  JTextField();
        jLabel8 = new  JLabel();
        jTextField16 = new  JTextField();
        jLabel9 = new  JLabel();
        jLabel35 = new  JLabel();
        jLabel36 = new  JLabel();
        jLabel37 = new  JLabel();
        jLabel38 = new  JLabel();
        jLabel39 = new  JLabel();
        jTextField17 = new  JTextField();
        jTextField18 = new  JTextField();
        jTextField19 = new  JTextField();
        jLabel40 = new  JLabel();
        jLabel41 = new  JLabel();
        jLabel42 = new  JLabel();
        jTextField20 = new  JTextField();
        jLabel43 = new  JLabel();
        jLabel44 = new  JLabel();
        jTextField21 = new  JTextField();
        jLabel45 = new  JLabel();
        jComboBox1 = new  JComboBox();
        jComboBox4 = new  JComboBox();
        jButton1 = new  JButton();
        jLabel46 = new  JLabel();
        jScrollPane2 = new  JScrollPane();
        jTextArea2 = new  JTextArea();
        canvas2 = new java.awt.Canvas();
        jLabel47 = new  JLabel();
        jLabel48 = new  JLabel();
        jLabel49 = new  JLabel();
        jLabel50 = new  JLabel();
        jLabel51 = new  JLabel();
        jLabel52 = new  JLabel();
        jLabel53 = new  JLabel();
        jButton2 = new  JButton();
        jFormattedTextField1 = new  JFormattedTextField();
        jFormattedTextField2 = new  JFormattedTextField();
        jFormattedTextField3 = new  JFormattedTextField();
        jLabel54 = new  JLabel();
        jFormattedTextField4 = new  JFormattedTextField();

        setDefaultCloseOperation( WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder( BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Transaction");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Update / View profile");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Transaction History");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

         GroupLayout jPanel1Layout = new  GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1,  GroupLayout.DEFAULT_SIZE,  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2,  GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3,  GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1,  GroupLayout.PREFERRED_SIZE, 27,  GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel2,  GroupLayout.PREFERRED_SIZE, 27,  GroupLayout.PREFERRED_SIZE)
                .addContainerGap( GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jLabel3,  GroupLayout.PREFERRED_SIZE, 27,  GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(660, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setAutoscrolls(true);
        jPanel2.setEnabled(false);

        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("First Name");
        jLabel4.setVerticalAlignment( SwingConstants.BOTTOM);

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setHorizontalAlignment( SwingConstants.LEFT);
        jLabel5.setText("Enter the Person Details");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Middle Name");
        jLabel6.setVerticalAlignment( SwingConstants.BOTTOM);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Last Name");
        jLabel7.setVerticalAlignment( SwingConstants.BOTTOM);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Email ID");
        jLabel8.setVerticalAlignment( SwingConstants.BOTTOM);

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Phone");
        jLabel9.setVerticalAlignment( SwingConstants.BOTTOM);

        jLabel35.setBackground(new java.awt.Color(255, 153, 0));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 102, 255));
        jLabel35.setHorizontalAlignment( SwingConstants.LEFT);
        jLabel35.setText("Address");

        jLabel36.setForeground(new java.awt.Color(51, 102, 255));
        jLabel36.setText("Street");
        jLabel36.setVerticalAlignment( SwingConstants.BOTTOM);

        jLabel37.setForeground(new java.awt.Color(51, 102, 255));
        jLabel37.setText("City");
        jLabel37.setVerticalAlignment( SwingConstants.BOTTOM);

        jLabel38.setForeground(new java.awt.Color(51, 102, 255));
        jLabel38.setText("Country");
        jLabel38.setVerticalAlignment( SwingConstants.BOTTOM);

        jLabel39.setForeground(new java.awt.Color(51, 102, 255));
        jLabel39.setText("Zip Code");
        jLabel39.setVerticalAlignment( SwingConstants.BOTTOM);

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jLabel40.setForeground(new java.awt.Color(51, 102, 255));
        jLabel40.setText("SSN");
        jLabel40.setVerticalAlignment( SwingConstants.BOTTOM);

        jLabel41.setBackground(new java.awt.Color(255, 153, 0));
        jLabel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 102, 255));
        jLabel41.setHorizontalAlignment( SwingConstants.LEFT);
        jLabel41.setText("Password Question");

        jLabel42.setForeground(new java.awt.Color(51, 102, 255));
        jLabel42.setText("Question 1");
        jLabel42.setVerticalAlignment( SwingConstants.BOTTOM);

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jLabel43.setForeground(new java.awt.Color(51, 102, 255));
        jLabel43.setText("Answer Hint");
        jLabel43.setVerticalAlignment( SwingConstants.BOTTOM);

        jLabel44.setForeground(new java.awt.Color(51, 102, 255));
        jLabel44.setText("Question 2");
        jLabel44.setVerticalAlignment( SwingConstants.BOTTOM);

        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });

        jLabel45.setForeground(new java.awt.Color(51, 102, 255));
        jLabel45.setText("Answer Hint");
        jLabel45.setVerticalAlignment( SwingConstants.BOTTOM);

        jComboBox1.setModel(new  DefaultComboBoxModel(new String[] { "Which City you were born?", "Maiden name of your mother?", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new  DefaultComboBoxModel(new String[] { "Name of your High school?", "Your first Applet program name?" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(new  javax.swing.border.SoftBevelBorder( javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel46.setForeground(new java.awt.Color(51, 102, 255));
        jLabel46.setText("Message");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        canvas2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel47.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 51, 0));
        jLabel47.setText("*");

        jLabel48.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 51, 0));
        jLabel48.setText("*");

        jLabel49.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 51, 0));
        jLabel49.setText("*");

        jLabel50.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 51, 0));
        jLabel50.setText("*");

        jLabel51.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 51, 0));
        jLabel51.setText("*");

        jLabel52.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 51, 0));
        jLabel52.setText("*");

        jLabel53.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 51, 0));
        jLabel53.setText("*");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 102, 255));
        jButton2.setText("Upload Photo");
        jButton2.setBorder(new  javax.swing.border.SoftBevelBorder( javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jFormattedTextField1.setFormatterFactory(new  javax.swing.text.DefaultFormatterFactory(new  javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jFormattedTextField2.setFormatterFactory(new  javax.swing.text.DefaultFormatterFactory(new  javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jFormattedTextField3.setFormatterFactory(new  javax.swing.text.DefaultFormatterFactory(new  javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jLabel54.setForeground(new java.awt.Color(51, 102, 255));
        jLabel54.setText("Date Of Birth");
        jLabel54.setVerticalAlignment( SwingConstants.BOTTOM);

        jFormattedTextField4.setFormatterFactory(new  javax.swing.text.DefaultFormatterFactory(new  javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });

         GroupLayout jPanel2Layout = new  GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField13,  GroupLayout.PREFERRED_SIZE, 187,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel49,  GroupLayout.PREFERRED_SIZE, 11,  GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel40,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextField1,  GroupLayout.PREFERRED_SIZE, 109,  GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextField3,  GroupLayout.PREFERRED_SIZE, 109,  GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel54,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField4,  GroupLayout.PREFERRED_SIZE, 109,  GroupLayout.PREFERRED_SIZE)))
                                .addGap(85, 85, 85)
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46,  GroupLayout.PREFERRED_SIZE, 115,  GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2,  GroupLayout.PREFERRED_SIZE, 237,  GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField15,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField11,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel47,  GroupLayout.PREFERRED_SIZE, 11,  GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField16,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel48,  GroupLayout.PREFERRED_SIZE, 11,  GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(canvas2,  GroupLayout.PREFERRED_SIZE, 151,  GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5,  GroupLayout.PREFERRED_SIZE, 382,  GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35,  GroupLayout.PREFERRED_SIZE, 382,  GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel37,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField18,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51,  GroupLayout.PREFERRED_SIZE, 11,  GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel36,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField19,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel50,  GroupLayout.PREFERRED_SIZE, 11,  GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.TRAILING)
                                    .addGroup( GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel39,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField2,  GroupLayout.PREFERRED_SIZE, 86,  GroupLayout.PREFERRED_SIZE))
                                    .addGroup( GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel38,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField17,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52,  GroupLayout.PREFERRED_SIZE, 11,  GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel53,  GroupLayout.PREFERRED_SIZE, 11,  GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel41,  GroupLayout.PREFERRED_SIZE, 382,  GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel43,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField20,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel42,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1,  GroupLayout.PREFERRED_SIZE, 182,  GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel44,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox4,  GroupLayout.PREFERRED_SIZE, 182,  GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1,  GroupLayout.Alignment.LEADING,  GroupLayout.DEFAULT_SIZE,  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup( GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel45,  GroupLayout.PREFERRED_SIZE, 95,  GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField21,  GroupLayout.PREFERRED_SIZE, 103,  GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel47))
                                .addPreferredGap( LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField15,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel48))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField16,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(canvas2,  GroupLayout.PREFERRED_SIZE, 88,  GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField13,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49))
                    .addComponent(jLabel8,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel46,  GroupLayout.PREFERRED_SIZE, 16,  GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2,  GroupLayout.PREFERRED_SIZE, 56,  GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField1,  GroupLayout.PREFERRED_SIZE,  GroupLayout.DEFAULT_SIZE,  GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField3,  GroupLayout.PREFERRED_SIZE,  GroupLayout.DEFAULT_SIZE,  GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField4,  GroupLayout.PREFERRED_SIZE,  GroupLayout.DEFAULT_SIZE,  GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel54,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(jFormattedTextField2,  GroupLayout.PREFERRED_SIZE,  GroupLayout.DEFAULT_SIZE,  GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1,  GroupLayout.PREFERRED_SIZE,  GroupLayout.DEFAULT_SIZE,  GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4,  GroupLayout.PREFERRED_SIZE,  GroupLayout.DEFAULT_SIZE,  GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup( GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45,  GroupLayout.PREFERRED_SIZE, 26,  GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21,  GroupLayout.PREFERRED_SIZE, 24,  GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1,  GroupLayout.PREFERRED_SIZE, 29,  GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

         GroupLayout layout = new  GroupLayout(rootPane);
        rootPane.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1,  GroupLayout.PREFERRED_SIZE,  GroupLayout.DEFAULT_SIZE,  GroupLayout.PREFERRED_SIZE)
                .addPreferredGap( LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1,  GroupLayout.PREFERRED_SIZE, 824,  GroupLayout.PREFERRED_SIZE)
                .addContainerGap( GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup( GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup( GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1,  GroupLayout.DEFAULT_SIZE,  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1,  GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE))
                .addContainerGap( GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    
    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    	
    	rootPane.removeAll();
    	new AccountView1(rootPane);
    	this.repaint();	
    }
    
    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    	
    	rootPane.removeAll();
    	new AccountView2(rootPane);
    	this.repaint();	
    }
    
    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private java.awt.Canvas canvas2;
    private  JButton jButton1;
    private  JButton jButton2;
    private  JComboBox jComboBox1;
    private  JComboBox jComboBox4;
    private  JFormattedTextField jFormattedTextField1;
    private  JFormattedTextField jFormattedTextField2;
    private  JFormattedTextField jFormattedTextField3;
    private  JFormattedTextField jFormattedTextField4;
    private  JLabel jLabel1;
    private  JLabel jLabel2;
    private  JLabel jLabel3;
    private  JLabel jLabel35;
    private  JLabel jLabel36;
    private  JLabel jLabel37;
    private  JLabel jLabel38;
    private  JLabel jLabel39;
    private  JLabel jLabel4;
    private  JLabel jLabel40;
    private  JLabel jLabel41;
    private  JLabel jLabel42;
    private  JLabel jLabel43;
    private  JLabel jLabel44;
    private  JLabel jLabel45;
    private  JLabel jLabel46;
    private  JLabel jLabel47;
    private  JLabel jLabel48;
    private  JLabel jLabel49;
    private  JLabel jLabel5;
    private  JLabel jLabel50;
    private  JLabel jLabel51;
    private  JLabel jLabel52;
    private  JLabel jLabel53;
    private  JLabel jLabel54;
    private  JLabel jLabel6;
    private  JLabel jLabel7;
    private  JLabel jLabel8;
    private  JLabel jLabel9;
    private  JPanel jPanel1;
    private  JPanel jPanel2;
    private  JScrollPane jScrollPane1;
    private  JScrollPane jScrollPane2;
    private  JTextArea jTextArea2;
    private  JTextField jTextField11;
    private  JTextField jTextField13;
    private  JTextField jTextField15;
    private  JTextField jTextField16;
    private  JTextField jTextField17;
    private  JTextField jTextField18;
    private  JTextField jTextField19;
    private  JTextField jTextField20;
    private  JTextField jTextField21;
    private Container rootPane;
    // End of variables declaration
}
  